"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe" -Xms512M -Xmx1024M -Xss1M -XX:+CMSClassUnloadingEnabled -javaagent:C:\Users\Kosuke\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\181.5540.7\lib\idea_rt.jar=51838:C:\Users\Kosuke\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\181.5540.7\bin -Dfile.encoding=windows-31j -classpath C:\Users\Kosuke\.IdeaIC2018.1\config\plugins\Scala\launcher\sbt-launch.jar xsbt.boot.Boot run
[info] Loading global plugins from C:\Users\Kosuke\.sbt\0.13\plugins
[info] Loading project definition from C:\tools\cygwin\home\Kosuke\sources\task-manager\project
[info] Set current project to task-manager (in build file:/C:/tools/cygwin/home/Kosuke/sources/task-manager/)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] Compiling 1 Scala source to C:\tools\cygwin\home\Kosuke\sources\task-manager\target\scala-2.12\classes...
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter

[info] play.api.Play - Application started (Dev)
[error] application -

! @78l6788hj - Internal server error, for (GET) [/tasks] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InvalidColumnNameException: Invalid column name. (name: m.content, registered names: id,subject,supporter,contents,create_at,update_at)]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:310)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:308)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Caused by: scalikejdbc.InvalidColumnNameException: Invalid column name. (name: m.content, registered names: id,subject,supporter,contents,create_at,update_at)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxProviderCommonImpl.notFoundInColumns(SQLSyntaxSupportFeature.scala:470)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxProviderCommonImpl.notFoundInColumns(SQLSyntaxSupportFeature.scala:467)
	at scalikejdbc.SQLSyntaxSupportFeature$BasicResultNameSQLSyntaxProvider.$anonfun$column$22(SQLSyntaxSupportFeature.scala:615)
	at scala.Option.getOrElse(Option.scala:121)
	at scalikejdbc.SQLSyntaxSupportFeature$BasicResultNameSQLSyntaxProvider.$anonfun$column$19(SQLSyntaxSupportFeature.scala:615)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at scalikejdbc.SQLSyntaxSupportFeature$BasicResultNameSQLSyntaxProvider.column(SQLSyntaxSupportFeature.scala:615)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxProvider.c(SQLSyntaxSupportFeature.scala:309)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxProvider.c$(SQLSyntaxSupportFeature.scala:309)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxProviderCommonImpl.c(SQLSyntaxSupportFeature.scala:458)
